# Generated by Django 6.0.2 on 2026-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='password',
            field=models.CharField(default='password123', max_length=100),
        ),
    ]
